# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Department.create(name:'Adquisiciones', manager_name:'Isaí Arenas Garibay')
Department.create(name:'Calidad', manager_name:'Bibiana Borja Blanco')
Department.create(name:'Control Patrimonial', manager_name:'Efraín Ramos Balderrama')
Department.create(name:'Laboratorio de Análisis Químicos', manager_name:'Q. Silvia V. Miranda Navarro')
Department.create(name:'Laboratorio Calidad del Aire')
Department.create(name:'Laboratorio Calidad del Agua')
Department.create(name:'Laboratorio de Corrosión y Protección', manager_name:'M.C Adán Borunda Terrazas')
Department.create(name:'Laboratorio de Espectroscopia de Infrarojo', manager_name:'Luis De La Torre')
Department.create(name:'Laboratorio de Metrología')
Department.create(name:'Laboratorio de Metrología Dimensional')
Department.create(name:'Laboratorio de Metrologia Eléctrica')
Department.create(name:'Laboratorio de Metrologia Humedad')
Department.create(name:'Laboratorio de Metrologia Masa')
Department.create(name:'Laboratorio Metrologia Presión')
Department.create(name:'Laboratorio Metrologia Temperatura')
Department.create(name:'Laboratorio de Metrologia Volumen')
Department.create(name:'Laboratorio de Nanotecnología')
Department.create(name:'Laboratorio Sientesis de Peliculas Delgadas')
Department.create(name:'Laboratorio de Pruebas Mecánicas')
Department.create(name:'Laboratorio de Pruebas No Destructivas')
Department.create(name:'Laboratorio de Residuos')
Department.create(name:'Laboratorio de Rayos X')
Department.create(name:'Mantenimiento')
Department.create(name:'Recursos Humanos')
Department.create(name:'Tecnologías de Información')